// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj-dWWKhTtV4KuwG3XWWsu2alxFTtWvWk',
    appId: '1:933093544643:web:bb946add5f11d06b1b0876',
    messagingSenderId: '933093544643',
    projectId: 'todo-list-84179',
    authDomain: 'todo-list-84179.firebaseapp.com',
    storageBucket: 'todo-list-84179.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZPbeQNLfciHDERSalsInLLNQHwSZ5o-g',
    appId: '1:933093544643:android:30d3cdb4a2c9fc4e1b0876',
    messagingSenderId: '933093544643',
    projectId: 'todo-list-84179',
    storageBucket: 'todo-list-84179.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE6JdiKC0RWkUqbyvz0I_3yM8abZiZZcU',
    appId: '1:933093544643:ios:de8930d25ca0ec621b0876',
    messagingSenderId: '933093544643',
    projectId: 'todo-list-84179',
    storageBucket: 'todo-list-84179.appspot.com',
    iosBundleId: 'com.todolist.app.todolist',
  );
}
